/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as AlertRulesIndexRouteImport } from './routes/alert-rules/index'
import { Route as AuditApiKeysIndexRouteImport } from './routes/audit-api-keys/index'
import { Route as AuditExportIndexRouteImport } from './routes/audit-export/index'
import { Route as AuditInferenceIndexRouteImport } from './routes/audit-inference/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as GpuQuotasIndexRouteImport } from './routes/gpu-quotas/index'
import { Route as GpuIndexRouteImport } from './routes/gpu/index'
import { Route as HealthGpuIndexRouteImport } from './routes/health-gpu/index'
import { Route as HealthInferenceIndexRouteImport } from './routes/health-inference/index'
import { Route as HealthKbIndexRouteImport } from './routes/health-kb/index'
import { Route as HealthIndexRouteImport } from './routes/health/index'
import { Route as IdpIndexRouteImport } from './routes/idp/index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as MeteringIndexRouteImport } from './routes/metering/index'
import { Route as MetricsIndexRouteImport } from './routes/metrics/index'
import { Route as NetworkIndexRouteImport } from './routes/network/index'
import { Route as NodesIndexRouteImport } from './routes/nodes/index'
import { Route as NotifyIndexRouteImport } from './routes/notify/index'
import { Route as OpsSystemIndexRouteImport } from './routes/ops-system/index'
import { Route as OverviewAlertsIndexRouteImport } from './routes/overview-alerts/index'
import { Route as OverviewInferenceIndexRouteImport } from './routes/overview-inference/index'
import { Route as OverviewKbIndexRouteImport } from './routes/overview-kb/index'
import { Route as PlatformAdminsIndexRouteImport } from './routes/platform-admins/index'
import { Route as PlatformAdminsUserIdRouteImport } from './routes/platform-admins/$userId'
import { Route as PlatformRolesIndexRouteImport } from './routes/platform-roles/index'
import { Route as PoolIndexRouteImport } from './routes/pool/index'
import { Route as RegistryGcIndexRouteImport } from './routes/registry-gc/index'
import { Route as RegistryQuotaIndexRouteImport } from './routes/registry-quota/index'
import { Route as RegistryVulnerabilitiesIndexRouteImport } from './routes/registry-vulnerabilities/index'
import { Route as SessionIndexRouteImport } from './routes/session/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as StorageQuotasIndexRouteImport } from './routes/storage-quotas/index'
import { Route as StorageIndexRouteImport } from './routes/storage/index'
import { Route as TenantUsageRankingIndexRouteImport } from './routes/tenant-usage-ranking/index'
import { Route as TenantsAdminsIndexRouteImport } from './routes/tenants-admins/index'
import { Route as TenantsAdminsAdminIdRouteImport } from './routes/tenants-admins/$adminId'
import { Route as TenantsBillingIndexRouteImport } from './routes/tenants-billing/index'
import { Route as TenantsBillingTenantIdRouteImport } from './routes/tenants-billing/$tenantId'
import { Route as TenantsQuotasIndexRouteImport } from './routes/tenants-quotas/index'
import { Route as TenantsQuotasPlanCodeRouteImport } from './routes/tenants-quotas/$planCode'
import { Route as TenantsIndexRouteImport } from './routes/tenants/index'
import { Route as TenantsTenantIdRouteImport } from './routes/tenants/$tenantId'
import { Route as TracesIndexRouteImport } from './routes/traces/index'
import { Route as WebhookIndexRouteImport } from './routes/webhook/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertRulesIndexRoute = AlertRulesIndexRouteImport.update({
  id: '/alert-rules/',
  path: '/alert-rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditApiKeysIndexRoute = AuditApiKeysIndexRouteImport.update({
  id: '/audit-api-keys/',
  path: '/audit-api-keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditExportIndexRoute = AuditExportIndexRouteImport.update({
  id: '/audit-export/',
  path: '/audit-export/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditInferenceIndexRoute = AuditInferenceIndexRouteImport.update({
  id: '/audit-inference/',
  path: '/audit-inference/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const GpuQuotasIndexRoute = GpuQuotasIndexRouteImport.update({
  id: '/gpu-quotas/',
  path: '/gpu-quotas/',
  getParentRoute: () => rootRouteImport,
} as any)
const GpuIndexRoute = GpuIndexRouteImport.update({
  id: '/gpu/',
  path: '/gpu/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthGpuIndexRoute = HealthGpuIndexRouteImport.update({
  id: '/health-gpu/',
  path: '/health-gpu/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthInferenceIndexRoute = HealthInferenceIndexRouteImport.update({
  id: '/health-inference/',
  path: '/health-inference/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthKbIndexRoute = HealthKbIndexRouteImport.update({
  id: '/health-kb/',
  path: '/health-kb/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdpIndexRoute = IdpIndexRouteImport.update({
  id: '/idp/',
  path: '/idp/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeteringIndexRoute = MeteringIndexRouteImport.update({
  id: '/metering/',
  path: '/metering/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIndexRoute = MetricsIndexRouteImport.update({
  id: '/metrics/',
  path: '/metrics/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkIndexRoute = NetworkIndexRouteImport.update({
  id: '/network/',
  path: '/network/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifyIndexRoute = NotifyIndexRouteImport.update({
  id: '/notify/',
  path: '/notify/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsSystemIndexRoute = OpsSystemIndexRouteImport.update({
  id: '/ops-system/',
  path: '/ops-system/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewAlertsIndexRoute = OverviewAlertsIndexRouteImport.update({
  id: '/overview-alerts/',
  path: '/overview-alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewInferenceIndexRoute = OverviewInferenceIndexRouteImport.update({
  id: '/overview-inference/',
  path: '/overview-inference/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewKbIndexRoute = OverviewKbIndexRouteImport.update({
  id: '/overview-kb/',
  path: '/overview-kb/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminsIndexRoute = PlatformAdminsIndexRouteImport.update({
  id: '/platform-admins/',
  path: '/platform-admins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminsUserIdRoute = PlatformAdminsUserIdRouteImport.update({
  id: '/platform-admins/$userId',
  path: '/platform-admins/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRolesIndexRoute = PlatformRolesIndexRouteImport.update({
  id: '/platform-roles/',
  path: '/platform-roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolIndexRoute = PoolIndexRouteImport.update({
  id: '/pool/',
  path: '/pool/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryGcIndexRoute = RegistryGcIndexRouteImport.update({
  id: '/registry-gc/',
  path: '/registry-gc/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryQuotaIndexRoute = RegistryQuotaIndexRouteImport.update({
  id: '/registry-quota/',
  path: '/registry-quota/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryVulnerabilitiesIndexRoute =
  RegistryVulnerabilitiesIndexRouteImport.update({
    id: '/registry-vulnerabilities/',
    path: '/registry-vulnerabilities/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageQuotasIndexRoute = StorageQuotasIndexRouteImport.update({
  id: '/storage-quotas/',
  path: '/storage-quotas/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageIndexRoute = StorageIndexRouteImport.update({
  id: '/storage/',
  path: '/storage/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantUsageRankingIndexRoute = TenantUsageRankingIndexRouteImport.update({
  id: '/tenant-usage-ranking/',
  path: '/tenant-usage-ranking/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsAdminsIndexRoute = TenantsAdminsIndexRouteImport.update({
  id: '/tenants-admins/',
  path: '/tenants-admins/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsAdminsAdminIdRoute = TenantsAdminsAdminIdRouteImport.update({
  id: '/tenants-admins/$adminId',
  path: '/tenants-admins/$adminId',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsBillingIndexRoute = TenantsBillingIndexRouteImport.update({
  id: '/tenants-billing/',
  path: '/tenants-billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsBillingTenantIdRoute = TenantsBillingTenantIdRouteImport.update({
  id: '/tenants-billing/$tenantId',
  path: '/tenants-billing/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsQuotasIndexRoute = TenantsQuotasIndexRouteImport.update({
  id: '/tenants-quotas/',
  path: '/tenants-quotas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsQuotasPlanCodeRoute = TenantsQuotasPlanCodeRouteImport.update({
  id: '/tenants-quotas/$planCode',
  path: '/tenants-quotas/$planCode',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantsRoute,
} as any)
const TenantsTenantIdRoute = TenantsTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => TenantsRoute,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookIndexRoute = WebhookIndexRouteImport.update({
  id: '/webhook/',
  path: '/webhook/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tenants': typeof TenantsRouteWithChildren
  '/platform-admins/$userId': typeof PlatformAdminsUserIdRoute
  '/tenants-admins/$adminId': typeof TenantsAdminsAdminIdRoute
  '/tenants-billing/$tenantId': typeof TenantsBillingTenantIdRoute
  '/tenants-quotas/$planCode': typeof TenantsQuotasPlanCodeRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/alert-rules/': typeof AlertRulesIndexRoute
  '/audit-api-keys/': typeof AuditApiKeysIndexRoute
  '/audit-export/': typeof AuditExportIndexRoute
  '/audit-inference/': typeof AuditInferenceIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/gpu-quotas/': typeof GpuQuotasIndexRoute
  '/gpu/': typeof GpuIndexRoute
  '/health-gpu/': typeof HealthGpuIndexRoute
  '/health-inference/': typeof HealthInferenceIndexRoute
  '/health-kb/': typeof HealthKbIndexRoute
  '/health/': typeof HealthIndexRoute
  '/idp/': typeof IdpIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/metering/': typeof MeteringIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/network/': typeof NetworkIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/notify/': typeof NotifyIndexRoute
  '/ops-system/': typeof OpsSystemIndexRoute
  '/overview-alerts/': typeof OverviewAlertsIndexRoute
  '/overview-inference/': typeof OverviewInferenceIndexRoute
  '/overview-kb/': typeof OverviewKbIndexRoute
  '/platform-admins/': typeof PlatformAdminsIndexRoute
  '/platform-roles/': typeof PlatformRolesIndexRoute
  '/pool/': typeof PoolIndexRoute
  '/registry-gc/': typeof RegistryGcIndexRoute
  '/registry-quota/': typeof RegistryQuotaIndexRoute
  '/registry-vulnerabilities/': typeof RegistryVulnerabilitiesIndexRoute
  '/session/': typeof SessionIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/storage-quotas/': typeof StorageQuotasIndexRoute
  '/storage/': typeof StorageIndexRoute
  '/tenant-usage-ranking/': typeof TenantUsageRankingIndexRoute
  '/tenants-admins/': typeof TenantsAdminsIndexRoute
  '/tenants-billing/': typeof TenantsBillingIndexRoute
  '/tenants-quotas/': typeof TenantsQuotasIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/webhook/': typeof WebhookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platform-admins/$userId': typeof PlatformAdminsUserIdRoute
  '/tenants-admins/$adminId': typeof TenantsAdminsAdminIdRoute
  '/tenants-billing/$tenantId': typeof TenantsBillingTenantIdRoute
  '/tenants-quotas/$planCode': typeof TenantsQuotasPlanCodeRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/alert-rules': typeof AlertRulesIndexRoute
  '/audit-api-keys': typeof AuditApiKeysIndexRoute
  '/audit-export': typeof AuditExportIndexRoute
  '/audit-inference': typeof AuditInferenceIndexRoute
  '/audit': typeof AuditIndexRoute
  '/gpu-quotas': typeof GpuQuotasIndexRoute
  '/gpu': typeof GpuIndexRoute
  '/health-gpu': typeof HealthGpuIndexRoute
  '/health-inference': typeof HealthInferenceIndexRoute
  '/health-kb': typeof HealthKbIndexRoute
  '/health': typeof HealthIndexRoute
  '/idp': typeof IdpIndexRoute
  '/incidents': typeof IncidentsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/login': typeof LoginIndexRoute
  '/logs': typeof LogsIndexRoute
  '/metering': typeof MeteringIndexRoute
  '/metrics': typeof MetricsIndexRoute
  '/network': typeof NetworkIndexRoute
  '/nodes': typeof NodesIndexRoute
  '/notify': typeof NotifyIndexRoute
  '/ops-system': typeof OpsSystemIndexRoute
  '/overview-alerts': typeof OverviewAlertsIndexRoute
  '/overview-inference': typeof OverviewInferenceIndexRoute
  '/overview-kb': typeof OverviewKbIndexRoute
  '/platform-admins': typeof PlatformAdminsIndexRoute
  '/platform-roles': typeof PlatformRolesIndexRoute
  '/pool': typeof PoolIndexRoute
  '/registry-gc': typeof RegistryGcIndexRoute
  '/registry-quota': typeof RegistryQuotaIndexRoute
  '/registry-vulnerabilities': typeof RegistryVulnerabilitiesIndexRoute
  '/session': typeof SessionIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/storage-quotas': typeof StorageQuotasIndexRoute
  '/storage': typeof StorageIndexRoute
  '/tenant-usage-ranking': typeof TenantUsageRankingIndexRoute
  '/tenants-admins': typeof TenantsAdminsIndexRoute
  '/tenants-billing': typeof TenantsBillingIndexRoute
  '/tenants-quotas': typeof TenantsQuotasIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/traces': typeof TracesIndexRoute
  '/webhook': typeof WebhookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tenants': typeof TenantsRouteWithChildren
  '/platform-admins/$userId': typeof PlatformAdminsUserIdRoute
  '/tenants-admins/$adminId': typeof TenantsAdminsAdminIdRoute
  '/tenants-billing/$tenantId': typeof TenantsBillingTenantIdRoute
  '/tenants-quotas/$planCode': typeof TenantsQuotasPlanCodeRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/alert-rules/': typeof AlertRulesIndexRoute
  '/audit-api-keys/': typeof AuditApiKeysIndexRoute
  '/audit-export/': typeof AuditExportIndexRoute
  '/audit-inference/': typeof AuditInferenceIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/gpu-quotas/': typeof GpuQuotasIndexRoute
  '/gpu/': typeof GpuIndexRoute
  '/health-gpu/': typeof HealthGpuIndexRoute
  '/health-inference/': typeof HealthInferenceIndexRoute
  '/health-kb/': typeof HealthKbIndexRoute
  '/health/': typeof HealthIndexRoute
  '/idp/': typeof IdpIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/metering/': typeof MeteringIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/network/': typeof NetworkIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/notify/': typeof NotifyIndexRoute
  '/ops-system/': typeof OpsSystemIndexRoute
  '/overview-alerts/': typeof OverviewAlertsIndexRoute
  '/overview-inference/': typeof OverviewInferenceIndexRoute
  '/overview-kb/': typeof OverviewKbIndexRoute
  '/platform-admins/': typeof PlatformAdminsIndexRoute
  '/platform-roles/': typeof PlatformRolesIndexRoute
  '/pool/': typeof PoolIndexRoute
  '/registry-gc/': typeof RegistryGcIndexRoute
  '/registry-quota/': typeof RegistryQuotaIndexRoute
  '/registry-vulnerabilities/': typeof RegistryVulnerabilitiesIndexRoute
  '/session/': typeof SessionIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/storage-quotas/': typeof StorageQuotasIndexRoute
  '/storage/': typeof StorageIndexRoute
  '/tenant-usage-ranking/': typeof TenantUsageRankingIndexRoute
  '/tenants-admins/': typeof TenantsAdminsIndexRoute
  '/tenants-billing/': typeof TenantsBillingIndexRoute
  '/tenants-quotas/': typeof TenantsQuotasIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/webhook/': typeof WebhookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tenants'
    | '/platform-admins/$userId'
    | '/tenants-admins/$adminId'
    | '/tenants-billing/$tenantId'
    | '/tenants-quotas/$planCode'
    | '/tenants/$tenantId'
    | '/alert-rules/'
    | '/audit-api-keys/'
    | '/audit-export/'
    | '/audit-inference/'
    | '/audit/'
    | '/gpu-quotas/'
    | '/gpu/'
    | '/health-gpu/'
    | '/health-inference/'
    | '/health-kb/'
    | '/health/'
    | '/idp/'
    | '/incidents/'
    | '/jobs/'
    | '/login/'
    | '/logs/'
    | '/metering/'
    | '/metrics/'
    | '/network/'
    | '/nodes/'
    | '/notify/'
    | '/ops-system/'
    | '/overview-alerts/'
    | '/overview-inference/'
    | '/overview-kb/'
    | '/platform-admins/'
    | '/platform-roles/'
    | '/pool/'
    | '/registry-gc/'
    | '/registry-quota/'
    | '/registry-vulnerabilities/'
    | '/session/'
    | '/skills/'
    | '/storage-quotas/'
    | '/storage/'
    | '/tenant-usage-ranking/'
    | '/tenants-admins/'
    | '/tenants-billing/'
    | '/tenants-quotas/'
    | '/tenants/'
    | '/traces/'
    | '/webhook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/platform-admins/$userId'
    | '/tenants-admins/$adminId'
    | '/tenants-billing/$tenantId'
    | '/tenants-quotas/$planCode'
    | '/tenants/$tenantId'
    | '/alert-rules'
    | '/audit-api-keys'
    | '/audit-export'
    | '/audit-inference'
    | '/audit'
    | '/gpu-quotas'
    | '/gpu'
    | '/health-gpu'
    | '/health-inference'
    | '/health-kb'
    | '/health'
    | '/idp'
    | '/incidents'
    | '/jobs'
    | '/login'
    | '/logs'
    | '/metering'
    | '/metrics'
    | '/network'
    | '/nodes'
    | '/notify'
    | '/ops-system'
    | '/overview-alerts'
    | '/overview-inference'
    | '/overview-kb'
    | '/platform-admins'
    | '/platform-roles'
    | '/pool'
    | '/registry-gc'
    | '/registry-quota'
    | '/registry-vulnerabilities'
    | '/session'
    | '/skills'
    | '/storage-quotas'
    | '/storage'
    | '/tenant-usage-ranking'
    | '/tenants-admins'
    | '/tenants-billing'
    | '/tenants-quotas'
    | '/tenants'
    | '/traces'
    | '/webhook'
  id:
    | '__root__'
    | '/'
    | '/tenants'
    | '/platform-admins/$userId'
    | '/tenants-admins/$adminId'
    | '/tenants-billing/$tenantId'
    | '/tenants-quotas/$planCode'
    | '/tenants/$tenantId'
    | '/alert-rules/'
    | '/audit-api-keys/'
    | '/audit-export/'
    | '/audit-inference/'
    | '/audit/'
    | '/gpu-quotas/'
    | '/gpu/'
    | '/health-gpu/'
    | '/health-inference/'
    | '/health-kb/'
    | '/health/'
    | '/idp/'
    | '/incidents/'
    | '/jobs/'
    | '/login/'
    | '/logs/'
    | '/metering/'
    | '/metrics/'
    | '/network/'
    | '/nodes/'
    | '/notify/'
    | '/ops-system/'
    | '/overview-alerts/'
    | '/overview-inference/'
    | '/overview-kb/'
    | '/platform-admins/'
    | '/platform-roles/'
    | '/pool/'
    | '/registry-gc/'
    | '/registry-quota/'
    | '/registry-vulnerabilities/'
    | '/session/'
    | '/skills/'
    | '/storage-quotas/'
    | '/storage/'
    | '/tenant-usage-ranking/'
    | '/tenants-admins/'
    | '/tenants-billing/'
    | '/tenants-quotas/'
    | '/tenants/'
    | '/traces/'
    | '/webhook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantsRoute: typeof TenantsRouteWithChildren
  PlatformAdminsUserIdRoute: typeof PlatformAdminsUserIdRoute
  TenantsAdminsAdminIdRoute: typeof TenantsAdminsAdminIdRoute
  TenantsBillingTenantIdRoute: typeof TenantsBillingTenantIdRoute
  TenantsQuotasPlanCodeRoute: typeof TenantsQuotasPlanCodeRoute
  AlertRulesIndexRoute: typeof AlertRulesIndexRoute
  AuditApiKeysIndexRoute: typeof AuditApiKeysIndexRoute
  AuditExportIndexRoute: typeof AuditExportIndexRoute
  AuditInferenceIndexRoute: typeof AuditInferenceIndexRoute
  AuditIndexRoute: typeof AuditIndexRoute
  GpuQuotasIndexRoute: typeof GpuQuotasIndexRoute
  GpuIndexRoute: typeof GpuIndexRoute
  HealthGpuIndexRoute: typeof HealthGpuIndexRoute
  HealthInferenceIndexRoute: typeof HealthInferenceIndexRoute
  HealthKbIndexRoute: typeof HealthKbIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  IdpIndexRoute: typeof IdpIndexRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  MeteringIndexRoute: typeof MeteringIndexRoute
  MetricsIndexRoute: typeof MetricsIndexRoute
  NetworkIndexRoute: typeof NetworkIndexRoute
  NodesIndexRoute: typeof NodesIndexRoute
  NotifyIndexRoute: typeof NotifyIndexRoute
  OpsSystemIndexRoute: typeof OpsSystemIndexRoute
  OverviewAlertsIndexRoute: typeof OverviewAlertsIndexRoute
  OverviewInferenceIndexRoute: typeof OverviewInferenceIndexRoute
  OverviewKbIndexRoute: typeof OverviewKbIndexRoute
  PlatformAdminsIndexRoute: typeof PlatformAdminsIndexRoute
  PlatformRolesIndexRoute: typeof PlatformRolesIndexRoute
  PoolIndexRoute: typeof PoolIndexRoute
  RegistryGcIndexRoute: typeof RegistryGcIndexRoute
  RegistryQuotaIndexRoute: typeof RegistryQuotaIndexRoute
  RegistryVulnerabilitiesIndexRoute: typeof RegistryVulnerabilitiesIndexRoute
  SessionIndexRoute: typeof SessionIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  StorageQuotasIndexRoute: typeof StorageQuotasIndexRoute
  StorageIndexRoute: typeof StorageIndexRoute
  TenantUsageRankingIndexRoute: typeof TenantUsageRankingIndexRoute
  TenantsAdminsIndexRoute: typeof TenantsAdminsIndexRoute
  TenantsBillingIndexRoute: typeof TenantsBillingIndexRoute
  TenantsQuotasIndexRoute: typeof TenantsQuotasIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
  WebhookIndexRoute: typeof WebhookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-rules/': {
      id: '/alert-rules/'
      path: '/alert-rules'
      fullPath: '/alert-rules/'
      preLoaderRoute: typeof AlertRulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-api-keys/': {
      id: '/audit-api-keys/'
      path: '/audit-api-keys'
      fullPath: '/audit-api-keys/'
      preLoaderRoute: typeof AuditApiKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-export/': {
      id: '/audit-export/'
      path: '/audit-export'
      fullPath: '/audit-export/'
      preLoaderRoute: typeof AuditExportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-inference/': {
      id: '/audit-inference/'
      path: '/audit-inference'
      fullPath: '/audit-inference/'
      preLoaderRoute: typeof AuditInferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpu-quotas/': {
      id: '/gpu-quotas/'
      path: '/gpu-quotas'
      fullPath: '/gpu-quotas/'
      preLoaderRoute: typeof GpuQuotasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpu/': {
      id: '/gpu/'
      path: '/gpu'
      fullPath: '/gpu/'
      preLoaderRoute: typeof GpuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-gpu/': {
      id: '/health-gpu/'
      path: '/health-gpu'
      fullPath: '/health-gpu/'
      preLoaderRoute: typeof HealthGpuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-inference/': {
      id: '/health-inference/'
      path: '/health-inference'
      fullPath: '/health-inference/'
      preLoaderRoute: typeof HealthInferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-kb/': {
      id: '/health-kb/'
      path: '/health-kb'
      fullPath: '/health-kb/'
      preLoaderRoute: typeof HealthKbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idp/': {
      id: '/idp/'
      path: '/idp'
      fullPath: '/idp/'
      preLoaderRoute: typeof IdpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metering/': {
      id: '/metering/'
      path: '/metering'
      fullPath: '/metering/'
      preLoaderRoute: typeof MeteringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/': {
      id: '/metrics/'
      path: '/metrics'
      fullPath: '/metrics/'
      preLoaderRoute: typeof MetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/': {
      id: '/network/'
      path: '/network'
      fullPath: '/network/'
      preLoaderRoute: typeof NetworkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify/': {
      id: '/notify/'
      path: '/notify'
      fullPath: '/notify/'
      preLoaderRoute: typeof NotifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-system/': {
      id: '/ops-system/'
      path: '/ops-system'
      fullPath: '/ops-system/'
      preLoaderRoute: typeof OpsSystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview-alerts/': {
      id: '/overview-alerts/'
      path: '/overview-alerts'
      fullPath: '/overview-alerts/'
      preLoaderRoute: typeof OverviewAlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview-inference/': {
      id: '/overview-inference/'
      path: '/overview-inference'
      fullPath: '/overview-inference/'
      preLoaderRoute: typeof OverviewInferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview-kb/': {
      id: '/overview-kb/'
      path: '/overview-kb'
      fullPath: '/overview-kb/'
      preLoaderRoute: typeof OverviewKbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admins/': {
      id: '/platform-admins/'
      path: '/platform-admins'
      fullPath: '/platform-admins/'
      preLoaderRoute: typeof PlatformAdminsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admins/$userId': {
      id: '/platform-admins/$userId'
      path: '/platform-admins/$userId'
      fullPath: '/platform-admins/$userId'
      preLoaderRoute: typeof PlatformAdminsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-roles/': {
      id: '/platform-roles/'
      path: '/platform-roles'
      fullPath: '/platform-roles/'
      preLoaderRoute: typeof PlatformRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/': {
      id: '/pool/'
      path: '/pool'
      fullPath: '/pool/'
      preLoaderRoute: typeof PoolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry-gc/': {
      id: '/registry-gc/'
      path: '/registry-gc'
      fullPath: '/registry-gc/'
      preLoaderRoute: typeof RegistryGcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry-quota/': {
      id: '/registry-quota/'
      path: '/registry-quota'
      fullPath: '/registry-quota/'
      preLoaderRoute: typeof RegistryQuotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry-vulnerabilities/': {
      id: '/registry-vulnerabilities/'
      path: '/registry-vulnerabilities'
      fullPath: '/registry-vulnerabilities/'
      preLoaderRoute: typeof RegistryVulnerabilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/session'
      fullPath: '/session/'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage-quotas/': {
      id: '/storage-quotas/'
      path: '/storage-quotas'
      fullPath: '/storage-quotas/'
      preLoaderRoute: typeof StorageQuotasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage/': {
      id: '/storage/'
      path: '/storage'
      fullPath: '/storage/'
      preLoaderRoute: typeof StorageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant-usage-ranking/': {
      id: '/tenant-usage-ranking/'
      path: '/tenant-usage-ranking'
      fullPath: '/tenant-usage-ranking/'
      preLoaderRoute: typeof TenantUsageRankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants-admins/': {
      id: '/tenants-admins/'
      path: '/tenants-admins'
      fullPath: '/tenants-admins/'
      preLoaderRoute: typeof TenantsAdminsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants-admins/$adminId': {
      id: '/tenants-admins/$adminId'
      path: '/tenants-admins/$adminId'
      fullPath: '/tenants-admins/$adminId'
      preLoaderRoute: typeof TenantsAdminsAdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants-billing/': {
      id: '/tenants-billing/'
      path: '/tenants-billing'
      fullPath: '/tenants-billing/'
      preLoaderRoute: typeof TenantsBillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants-billing/$tenantId': {
      id: '/tenants-billing/$tenantId'
      path: '/tenants-billing/$tenantId'
      fullPath: '/tenants-billing/$tenantId'
      preLoaderRoute: typeof TenantsBillingTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants-quotas/': {
      id: '/tenants-quotas/'
      path: '/tenants-quotas'
      fullPath: '/tenants-quotas/'
      preLoaderRoute: typeof TenantsQuotasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants-quotas/$planCode': {
      id: '/tenants-quotas/$planCode'
      path: '/tenants-quotas/$planCode'
      fullPath: '/tenants-quotas/$planCode'
      preLoaderRoute: typeof TenantsQuotasPlanCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof TenantsRoute
    }
    '/tenants/$tenantId': {
      id: '/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof TenantsTenantIdRouteImport
      parentRoute: typeof TenantsRoute
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/': {
      id: '/webhook/'
      path: '/webhook'
      fullPath: '/webhook/'
      preLoaderRoute: typeof WebhookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TenantsRouteChildren {
  TenantsTenantIdRoute: typeof TenantsTenantIdRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
}

const TenantsRouteChildren: TenantsRouteChildren = {
  TenantsTenantIdRoute: TenantsTenantIdRoute,
  TenantsIndexRoute: TenantsIndexRoute,
}

const TenantsRouteWithChildren =
  TenantsRoute._addFileChildren(TenantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantsRoute: TenantsRouteWithChildren,
  PlatformAdminsUserIdRoute: PlatformAdminsUserIdRoute,
  TenantsAdminsAdminIdRoute: TenantsAdminsAdminIdRoute,
  TenantsBillingTenantIdRoute: TenantsBillingTenantIdRoute,
  TenantsQuotasPlanCodeRoute: TenantsQuotasPlanCodeRoute,
  AlertRulesIndexRoute: AlertRulesIndexRoute,
  AuditApiKeysIndexRoute: AuditApiKeysIndexRoute,
  AuditExportIndexRoute: AuditExportIndexRoute,
  AuditInferenceIndexRoute: AuditInferenceIndexRoute,
  AuditIndexRoute: AuditIndexRoute,
  GpuQuotasIndexRoute: GpuQuotasIndexRoute,
  GpuIndexRoute: GpuIndexRoute,
  HealthGpuIndexRoute: HealthGpuIndexRoute,
  HealthInferenceIndexRoute: HealthInferenceIndexRoute,
  HealthKbIndexRoute: HealthKbIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  IdpIndexRoute: IdpIndexRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  MeteringIndexRoute: MeteringIndexRoute,
  MetricsIndexRoute: MetricsIndexRoute,
  NetworkIndexRoute: NetworkIndexRoute,
  NodesIndexRoute: NodesIndexRoute,
  NotifyIndexRoute: NotifyIndexRoute,
  OpsSystemIndexRoute: OpsSystemIndexRoute,
  OverviewAlertsIndexRoute: OverviewAlertsIndexRoute,
  OverviewInferenceIndexRoute: OverviewInferenceIndexRoute,
  OverviewKbIndexRoute: OverviewKbIndexRoute,
  PlatformAdminsIndexRoute: PlatformAdminsIndexRoute,
  PlatformRolesIndexRoute: PlatformRolesIndexRoute,
  PoolIndexRoute: PoolIndexRoute,
  RegistryGcIndexRoute: RegistryGcIndexRoute,
  RegistryQuotaIndexRoute: RegistryQuotaIndexRoute,
  RegistryVulnerabilitiesIndexRoute: RegistryVulnerabilitiesIndexRoute,
  SessionIndexRoute: SessionIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  StorageQuotasIndexRoute: StorageQuotasIndexRoute,
  StorageIndexRoute: StorageIndexRoute,
  TenantUsageRankingIndexRoute: TenantUsageRankingIndexRoute,
  TenantsAdminsIndexRoute: TenantsAdminsIndexRoute,
  TenantsBillingIndexRoute: TenantsBillingIndexRoute,
  TenantsQuotasIndexRoute: TenantsQuotasIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
  WebhookIndexRoute: WebhookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
